import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {NavigationMenu, NavigationMenuItem, NavigationMenuLink, NavigationMenuList} from "@/components/ui/navigation-menu.tsx";
import Link from "next/link";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Horologium",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex justify-center">
      <NavigationMenu className="w-full bg-[oklch(0.1_0_0)] border-b shadow-sm px-6 py-3">
          <NavigationMenuList className="flex gap-6">
              <NavigationMenuLink asChild>
                  <Link href="/home" className="text-sm font-medium hover:text-primary transition">
                      Home
                  </Link>
              </NavigationMenuLink>
              <NavigationMenuLink asChild>
                  <Link href="/games" className="text-sm font-medium hover:text-primary transition">
                      Games
                  </Link>
              </NavigationMenuLink>
          </NavigationMenuList>
      </NavigationMenu>
      </div>

      {children}
      </body>
    </html>
  );
}
